server:
  port: ${SERVER_PORT:0}

grpc:
  server:
    port: 0

spring:
  output.ansi.enabled: ALWAYS
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topics:
    user-actions: stats.user-actions.v1