server.port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:stats-db;
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging.level:
  org.springframework:
    orm.jpa: INFO
    transaction: INFO
    transaction.interceptor: INFO
    orm.jpa.JpaTransactionManager: DEBUG
  org.zalando.logbook: TRACE
  ru.practicum: DEBUG
