server:
  port: 0

spring:
  output.ansi.enabled: ALWAYS
  sql.init.mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/ewm_request
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  jackson:
    serialization.write-dates-as-timestamps: false

logging:
  level:
    "org.zalando.logbook": TRACE
    "org.springframework.orm.jpa": INFO
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE
    org.springframework.jdbc.datasource.init: DEBUG