server:
  port: 8080

spring:
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: subscription-service-route
              uri: lb://subscription-service
              predicates:
                - Path=/users/{userId}/subscriptions/**,/users/{userId}/events/feed

            - id: request-service-route
              uri: lb://request-service
              predicates:
                - Path=/users/{userId}/requests/**

            - id: event-service-route
              uri: lb://event-service
              predicates:
                - Path=/**