server.port: 8080

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: subscription-service-route
              uri: lb://subscription-service
              predicates:
                - Path=/users/{userId}/subscriptions/**,/users/{userId}/events/feed

            - id: request-service-route
              uri: lb://request-service
              predicates:
                - Path=/users/{userId}/requests/**

            - id: event-service-route
              uri: lb://event-service
              predicates:
                - Path=/**