spring:
  cloud:
    gateway:
      discovery:
        locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/main-service/**

server:
  port: 8080