server:
  port: ${SERVER_PORT:0}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:0}

spring:
  output.ansi.enabled: ALWAYS
  sql.init.mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/ewm_rating
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none

analyzer:
  interaction:
    kafka:
      consumer:
        properties:
          enable.auto.commit: true
          bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.practicum.avro.deserializer.UserActionAvroDeserializer
          group.id: stats.analyzer.interaction
          auto.offset.reset: latest
          max.poll.interval.ms: 300000
          max.poll.records: 500
        topic: stats.user-actions.v1
        pool-timeout: 10000ms

  similarity:
    kafka:
      consumer:
        properties:
          enable.auto.commit: true
          bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.practicum.avro.deserializer.EventSimilarityAvroDeserializer
          group.id: stats.analyzer.similarity
          auto.offset.reset: latest
          max.poll.interval.ms: 300000
          max.poll.records: 500
        topic: stats.events-similarity.v1
        pool-timeout: 10000ms





