server:
  port: ${SERVER_PORT:0}

spring:
  output.ansi.enabled: ALWAYS
  sql.init.mode: always

  datasource:
    url: jdbc:h2:mem:stats-db
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    ru.practicum: INFO
    org.springframework.jdbc.datasource.init: DEBUG