server.port: 0

spring:
  output.ansi.enabled: ALWAYS
  sql.init.mode: always

  datasource:
    url: jdbc:h2:mem:stats-db
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging.level:
  ru.practicum: INFO
  org.springframework.jdbc.datasource.init: DEBUG