server:
  port: ${SERVER_PORT:0}

spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/ewm_stats_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    ru.practicum: INFO
    org.springframework.jdbc.datasource.init: DEBUG